version: '3.7'
services:
  jenkins:
    build: ./
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      # - 50000:50000
    container_name: jenkins-lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
  vault:
    image: hashicorp/vault:1.15
    restart: always
    ports:
      - "8200:8200/tcp"
    environment:
      # VAULT_DEV_ROOT_TOKEN_ID: 'root'
      # VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
      VAULT_ADDR: 'http://0.0.0.0:8200'
      # VAULT_API_ADDR: 'http://0.0.0.0:8100'
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: vault server -config=/vault/config/vault.json
    volumes:
      - ./vault/config:/vault/config:rw
      - ./vault/file/:/vault/file/:rw
      - ./vault/logs/:/vault/logs/:rw
