---
- name: Reload NetworkManager Service after Updating Configuration
  hosts: "{{ host }}"
  become: yes
  become_method: sudo

  tasks:

    - name: Copy updated configuration file
      copy:
        content: "{{ lookup('file', '{{ src_path }}') }}"
        dest: "{{ dest_path }}"

    - name: Apply Netplan Configuration
      command: netplan --debug apply
      register: netplan_output
      
    - name: Show Netplan apply output
      debug:
        var: netplan_output.stdout