---
- name: Restart Service after Updating Configuration
  hosts: "{{ host }}"
  become: yes
  become_method: sudo

  tasks:

    - name: Copy updated configuration file
      copy:
        content: "{{ lookup('file', '{{ src_path }}') }}"
        dest: "{{ dest_path }}"

    - name: Restart Service
      become: yes
      service:
        name: "{{ service }}"
        state: restarted
