---
- name: Restart Service after Updating Configuration
  hosts: "{{ host }}"
  become: yes
  become_method: sudo

  tasks:

    - name: Copy updated configuration file
      copy:
        content: "{{ lookup('file', '{{ src_path }}') }}"
        dest: "{{ dest_path }}"

    - name: Reload Daemon
      include_role:
        name: linux_daemon_reload
      when: daemon_reload | bool
      tags: reload_daemon

    - name: Reload Service
      include_role:
        name: linux_service_reload
      when: service_reload | bool
      tags: reload_service

    - name: Restart Service
      include_role:
        name: linux_service_restart
      when: service_restart | bool
      tags: restart_service
