---
- name: Send notification to Google Chat if {{ service }} doesn't exist
  uri:
    url: "#WEBHOOK"
    method: POST
    body_format: json
    body: '{"text": "The {{ service }} does not exist and could not be restarted"}'
    status_code: 200
    headers:
      Content-Type: "application/json"
