---
- name: Doing Compose down if it exists
  become: yes
  shell: "docker compose --project-name={{ project }} -f {{ dest_path }} down"
  register: container_info

- name: Show Netplan apply output
  debug:
    var: container_info

- name: Dowing Compose up if it exists
  become: yes
  shell: "docker compose --project-name={{ project }} -f {{ dest_path }} up -d"
  register: container_info

- name: Show Netplan apply output
  debug:
    var: container_info